version: 2

models:
  - name: daily_metrics
    description: "Daily aggregated gameplay/monetization/performance metrics."
    columns:
      - name: event_date
        tests: [not_null]
      - name: country
        tests: [not_null]
      - name: platform
        tests: [not_null]
      - name: DAU
        tests: [not_null]
